insert into attribute (attr,name,section,value) values ('li','ruth_main','navbar','1');
insert into attribute (attr,name,section,value) values ('nl','valid_perms','i18n','U heeft niet voldoende rechten voor deze operatie : ');
insert into attribute (attr,name,section,value) values ('nl','enter_name','i18n','Naam invoegen');
insert into attribute (attr,name,section,value) values ('nl','create_adminaccess','i18n','Nieuwe toegangsrechten toevoegen<br>');
insert into attribute (attr,name,section,value) values ('nl','remove_adminaccess','i18n','Toegangsrechten verwijderen<br> ');
insert into attribute (attr,name,section,value) values ('nl','save_adminaccess','i18n','Toegangsrechten opslaan<br>');
insert into attribute (attr,name,section,value) values ('nl','adminaccess_exists','i18n','Deze toegangsrechten bestaan reeds!<br>');
insert into attribute (attr,name,section,value) values ('nl','adminaccess_not_exists','i18n','Deze toegangsrechten bestaan niet!<br>');
insert into attribute (attr,name,section,value) values ('nl','create_content','i18n','Nieuwe content aanmaken<br>');
insert into attribute (attr,name,section,value) values ('nl','remove_content','i18n','Content verwijderen<br>');
insert into attribute (attr,name,section,value) values ('nl','edit_content','i18n','Content wijzigen<br>');
insert into attribute (attr,name,section,value) values ('nl','save_content','i18n','Content opslaan<br>');
insert into attribute (attr,name,section,value) values ('nl','copy_content','i18n','Content kopieren<br>');
insert into attribute (attr,name,section,value) values ('nl','content_exists','i18n','Deze content bestaat reeds!<br>');
insert into attribute (attr,name,section,value) values ('nl','content_not_exists','i18n','Deze content bestaat niet!<br>');
insert into attribute (attr,name,section,value) values ('nl','create_style','i18n','Nieuwe style aanmaken<br>');
insert into attribute (attr,name,section,value) values ('nl','remove_style','i18n','Style verwijderen<br>');
insert into attribute (attr,name,section,value) values ('nl','edit_style','i18n','Style wijzigen<br>');
insert into attribute (attr,name,section,value) values ('nl','save_style','i18n','Style opslaan<br>');
insert into attribute (attr,name,section,value) values ('nl','copy_style','i18n','Style kopieren<br>');
insert into attribute (attr,name,section,value) values ('nl','style_exists','i18n','Deze style bestaat reeds!<br>');
insert into attribute (attr,name,section,value) values ('nl','style_not_exists','i18n','Deze style bestaat niet!<br>');
insert into attribute (attr,name,section,value) values ('nl','new_upload','i18n','Upload een bestand<br>');
insert into attribute (attr,name,section,value) values ('nl','new_folder','i18n','Folder aanmaken<br>');
insert into attribute (attr,name,section,value) values ('nl','copy_file','i18n','Bestand kopieren<br>');
insert into attribute (attr,name,section,value) values ('nl','rename_file','i18n','Bestand van naam veranderen<br>');
insert into attribute (attr,name,section,value) values ('nl','read_folder','i18n','Inhoud van de folder lezen<br> ');
insert into attribute (attr,name,section,value) values ('nl','mkdir_failed','i18n','Folder kan niet aangemaakt worden.');
insert into attribute (attr,name,section,value) values ('nl','copy_failed','i18n','Bestand kan niet gekopieerd worden.');
insert into attribute (attr,name,section,value) values ('nl','remove_failed','i18n','Bestand kan niet verwijderd worden.');
insert into attribute (attr,name,section,value) values ('nl','rename_failed','i18n','Bestand kan niet van naam veranderd worden.');
insert into attribute (attr,name,section,value) values ('nl','readdir_failed','i18n','Inhoud van folder kan niet gelezen worden.');
insert into attribute (attr,name,section,value) values ('nl','docroot_permissions','i18n','Heeft document root correcte toegangsrechten?');
insert into attribute (attr,name,section,value) values ('nl','upload_failed','i18n','Bestand kan niet geupload worden. Rapporteer een programmafout als dit een blijvend probleem is.');
insert into attribute (attr,name,section,value) values ('nl','upload_unknown','i18n','Fout bij het aanmaken van het bestand:');
insert into attribute (attr,name,section,value) values ('nl','file_exists','i18n','Dit bestand bestaat reeds!<br>');
insert into attribute (attr,name,section,value) values ('nl','file_not_exists','i18n','Dit bestand bestaat niet!<br>');
insert into attribute (attr,name,section,value) values ('nl','folder_exists','i18n','Deze folder bestaat reeds!<br>');
insert into attribute (attr,name,section,value) values ('nl','folder_not_exists','i18n','Deze folder bestaat niet!<br>');
insert into attribute (attr,name,section,value) values ('nl','create_message','i18n','Nieuw bericht toevoegen<br>');
insert into attribute (attr,name,section,value) values ('nl','remove_message','i18n','Bericht verwijderen<br>');
insert into attribute (attr,name,section,value) values ('nl','edit_message','i18n','Bericht wijzigen<br>');
insert into attribute (attr,name,section,value) values ('nl','save_message','i18n','Bericht opslaan<br>');
insert into attribute (attr,name,section,value) values ('nl','save_messagegroup','i18n','Berichtengroep opslaan<br>');
insert into attribute (attr,name,section,value) values ('nl','copy_messagegroup','i18n','Berichtengroep kopieren<br> ');
insert into attribute (attr,name,section,value) values ('nl','messagegroup_exists','i18n','Deze berichtengroep bestaat reeds!<br>');
insert into attribute (attr,name,section,value) values ('nl','messagegroup_not_exists','i18n','Deze berichtengroep bestaat niet!<br> ');
insert into attribute (attr,name,section,value) values ('nl','view_stats','i18n','Statistieken bekijken<br>');
insert into attribute (attr,name,section,value) values ('nl','remove_stats','i18n','Statistieken verwijderen<br>');

insert into attribute (attr,name,section,value) values ('en','add_button','i18n','Add a button to the navigation bar');
insert into attribute (attr,name,section,value) values ('en','adminaccess_exists','i18n','These admin access permissions already exist!');
insert into attribute (attr,name,section,value) values ('en','adminaccess_not_exists','i18n','These admin access permissions do not exist!');
insert into attribute (attr,name,section,value) values ('en','content_exists','i18n','This content already exists!');
insert into attribute (attr,name,section,value) values ('en','content_not_exists','i18n','This content does not exist!');
insert into attribute (attr,name,section,value) values ('en','copy_content','i18n','Copy a content');
insert into attribute (attr,name,section,value) values ('en','copy_failed','i18n','Unable to copy file.');
insert into attribute (attr,name,section,value) values ('en','copy_file','i18n','Copy a file');
insert into attribute (attr,name,section,value) values ('en','copy_macroset','i18n','Copy a macroset');
insert into attribute (attr,name,section,value) values ('en','copy_messagegroup','i18n','Copy a messagegroup');
insert into attribute (attr,name,section,value) values ('en','copy_navbar','i18n','Copy a navigation bar');
insert into attribute (attr,name,section,value) values ('en','copy_style','i18n','Copy style');
insert into attribute (attr,name,section,value) values ('en','create_adminaccess','i18n','Add new admin access permissions');
insert into attribute (attr,name,section,value) values ('en','create_content','i18n','Create a new content');
insert into attribute (attr,name,section,value) values ('en','create_filetype','i18n','Add new filetype association');
insert into attribute (attr,name,section,value) values ('en','create_macro','i18n','Add a new macro');
insert into attribute (attr,name,section,value) values ('en','create_macroset','i18n','Add a new macroset');
insert into attribute (attr,name,section,value) values ('en','create_message','i18n','Create a new message');
insert into attribute (attr,name,section,value) values ('en','create_navbar','i18n','Create a new navigation bar');
insert into attribute (attr,name,section,value) values ('en','create_style','i18n','Create new style');
insert into attribute (attr,name,section,value) values ('en','create_user','i18n','Add a new user');
insert into attribute (attr,name,section,value) values ('en','create_usergroup','i18n','Add a user to a usergroup');
insert into attribute (attr,name,section,value) values ('en','delete_button','i18n','Delete a button from the navigation bar');
insert into attribute (attr,name,section,value) values ('en','docroot_permissions','i18n','Does the document root directory have correct permissions?');
insert into attribute (attr,name,section,value) values ('en','edit_button','i18n','Edit a button in the navigation bar');
insert into attribute (attr,name,section,value) values ('en','edit_content','i18n','Edit a content');
insert into attribute (attr,name,section,value) values ('en','edit_macroset','i18n','Edit a macroset');
insert into attribute (attr,name,section,value) values ('en','edit_message','i18n','Edit a message');
insert into attribute (attr,name,section,value) values ('en','edit_navbar','i18n','Edit a navigation bar');
insert into attribute (attr,name,section,value) values ('en','edit_style','i18n','Edit style');
insert into attribute (attr,name,section,value) values ('en','edit_user','i18n','Edit a user');
insert into attribute (attr,name,section,value) values ('en','enter_name','i18n','Enter name');
insert into attribute (attr,name,section,value) values ('en','file_exists','i18n','This file already exists!');
insert into attribute (attr,name,section,value) values ('en','file_not_exists','i18n','This file does not exists!');
insert into attribute (attr,name,section,value) values ('en','filetype_exists','i18n','This filetype association already exists!');
insert into attribute (attr,name,section,value) values ('en','filetype_not_exists','i18n','This filetype association does not exist!');
insert into attribute (attr,name,section,value) values ('en','folder_exists','i18n',' This folder already exists!');
insert into attribute (attr,name,section,value) values ('en','folder_not_exists','i18n',' This folder does not exist!');
insert into attribute (attr,name,section,value) values ('en','macroset_exists','i18n','This macroset already exists!');
insert into attribute (attr,name,section,value) values ('en','macroset_not_exists','i18n','This macroset does not exist!');
insert into attribute (attr,name,section,value) values ('en','messagegroup_exists','i18n','This messagegroup already exists!');
insert into attribute (attr,name,section,value) values ('en','messagegroup_not_exists','i18n','This messagegroup does not exist!');
insert into attribute (attr,name,section,value) values ('en','mkdir_failed','i18n','Unable to create folder.');
insert into attribute (attr,name,section,value) values ('en','navbar_exists','i18n','This navigation bar already exists!');
insert into attribute (attr,name,section,value) values ('en','navbar_not_exists','i18n','This navigation bar does not exist!');
insert into attribute (attr,name,section,value) values ('en','new_folder','i18n','Create a folder');
insert into attribute (attr,name,section,value) values ('en','new_upload','i18n','Upload a file');
insert into attribute (attr,name,section,value) values ('en','read_folder','i18n','Read folder contents');
insert into attribute (attr,name,section,value) values ('en','readdir_failed','i18n','Unable to read folder.');
insert into attribute (attr,name,section,value) values ('en','remove_adminaccess','i18n','Remove admin access permissions');
insert into attribute (attr,name,section,value) values ('en','remove_content','i18n','Remove a content');
insert into attribute (attr,name,section,value) values ('en','remove_failed','i18n','Unable to remove file.');
insert into attribute (attr,name,section,value) values ('en','remove_filetype','i18n','Remove filetype association');
insert into attribute (attr,name,section,value) values ('en','remove_macro','i18n','Remove a macro');
insert into attribute (attr,name,section,value) values ('en','remove_macroset','i18n','Remove a macroset');
insert into attribute (attr,name,section,value) values ('en','remove_message','i18n','Remove a message');
insert into attribute (attr,name,section,value) values ('en','remove_messagegroup','i18n','Remove a messagegroup');
insert into attribute (attr,name,section,value) values ('en','remove_navbar','i18n','Remove a navigation bar');
insert into attribute (attr,name,section,value) values ('en','remove_stats','i18n','Remove statistics');
insert into attribute (attr,name,section,value) values ('en','remove_style','i18n','Remove style');
insert into attribute (attr,name,section,value) values ('en','remove_user','i18n','Remove a user');
insert into attribute (attr,name,section,value) values ('en','remove_usergroup','i18n','Remove a user from a usergroup');
insert into attribute (attr,name,section,value) values ('en','rename_failed','i18n','Unable to rename file.');
insert into attribute (attr,name,section,value) values ('en','rename_file','i18n','Rename a file');
insert into attribute (attr,name,section,value) values ('en','save_adminaccess','i18n','Save admin access permissions');
insert into attribute (attr,name,section,value) values ('en','save_content','i18n','Save a content');
insert into attribute (attr,name,section,value) values ('en','save_filetype','i18n','Save filetype association');
insert into attribute (attr,name,section,value) values ('en','save_macro','i18n','Save a macro');
insert into attribute (attr,name,section,value) values ('en','save_message','i18n','Save a message');
insert into attribute (attr,name,section,value) values ('en','save_messagegroup','i18n','Save a messagegroup');
insert into attribute (attr,name,section,value) values ('en','save_navbar','i18n','Save a navigation bar');
insert into attribute (attr,name,section,value) values ('en','save_style','i18n','Save style');
insert into attribute (attr,name,section,value) values ('en','save_user','i18n','Save a user');
insert into attribute (attr,name,section,value) values ('en','style_exists','i18n','This style already exists!');
insert into attribute (attr,name,section,value) values ('en','style_not_exists','i18n','This style does not exist!');
insert into attribute (attr,name,section,value) values ('en','upload_failed','i18n','File could not be uploaded. If this problem persists, submit a bug report.');
insert into attribute (attr,name,section,value) values ('en','upload_unknown','i18n','Error creating file:');
insert into attribute (attr,name,section,value) values ('en','user_exists','i18n','This user already exists!');
insert into attribute (attr,name,section,value) values ('en','user_not_exists','i18n','This user does not exist!');
insert into attribute (attr,name,section,value) values ('en','usergroup_exists','i18n','This user is already part of this usergroup!');
insert into attribute (attr,name,section,value) values ('en','valid_perms','i18n','You do not have valid permissions for this operation : ');
insert into attribute (attr,name,section,value) values ('en','view_stats','i18n','View statistics');

insert into attribute (attr,name,section,value) values ('admin','lang','default','en');
insert into attribute (attr,name,section,value) values ('order','news','message','desc');
insert into attribute (attr,name,section,value) values ('txt','content','mimetype','text/plain');
insert into attribute (attr,name,section,value) values ('shtml','content','mimetype','text/html');
insert into attribute (attr,name,section,value) values ('css','content','mimetype','text/css');
insert into attribute (attr,name,section,value) values ('svgz','content','mimetype','image/svg+xml');
insert into attribute (attr,name,section,value) values ('svg','content','mimetype','image/svg+xml');
insert into attribute (attr,name,section,value) values ('png','content','mimetype','image/png');
insert into attribute (attr,name,section,value) values ('gif','content','mimetype','image/gif');
insert into attribute (attr,name,section,value) values ('jpe','content','mimetype','image/jpeg');
insert into attribute (attr,name,section,value) values ('jpeg','content','mimetype','image/jpeg');
insert into attribute (attr,name,section,value) values ('jpg','content','mimetype','image/jpeg');
insert into attribute (attr,name,section,value) values ('js','content','mimetype','application/x-javascript');
insert into attribute (attr,name,section,value) values ('xsl','content','mimetype','application/xml');
insert into attribute (attr,name,section,value) values ('xml','content','mimetype','application/xml');
insert into attribute (attr,name,section,value) values ('xhtml','content','mimetype','application/xhtml+xml');
insert into attribute (attr,name,section,value) values ('xht','content','mimetype','application/xhtml+xml');
insert into attribute (attr,name,section,value) values ('rdf','content','mimetype','application/rdf+xml');
insert into attribute (attr,name,section,value) values ('rss','content','mimetype','application/rss+xml');
insert into attribute (attr,name,section,value) values ('xml','content','mimetype','text/xml');
insert into attribute (attr,name,section,value) values ('htm','content','mimetype','text/html');
insert into attribute (attr,name,section,value) values ('html','content','mimetype','text/html');

