insert into message (body,mdate,mgroup,owner,parent,subject) values ('We proudly announce a new beta release, version 1.0_05, aptly codenamed <i>Taj Mahal</i>.\r\nThis version introduces a feature freeze. All known issues and bugs will be fixed. Check the ChangeLog listing for all changes in this\r\nrelease and the Download section to get it now! \r\n','2005-07-23 13:25:13','news','Owner','0','New Beta release');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.1 (codename Burton) is the new stable release. Major changes include:\r\n<dir><li>Updated layout and new styles</li>\r\n<li>Fixed large number of bugs</li>\r\n<li>Added File Manager and Administration Access control</li>\r\n</dir>See the <a href=\"changelog.html\">ChangeLog</a> for full listing.','2006-02-19 15:13:55','news','Owner','0','Released v1.1 Stable (Burton)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.2 beta (codename Baldrick) is a beta for the upcoming version 1.2 release. Major changes include:\r\n\r\n<dir><li>Updated layout and new styles</li>\r\n<li>Fixed small number of bugs</li>\r\n<li>Support for mod_perl 2</li>\r\n<li>Support for int\'l</li>\r\n<li>Support for Postgresql as RDBMS</li>\r\n</dir>See the <a href=\"changelog.html\">ChangeLog</a> for full listing.\r\n','2006-05-16 23:12:44','news','Owner','0','Released v1.2 Beta (Baldrick)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('SPINE has been under development for roughly 5 years. The mod_perl version was released 2 years ago. We\'re approaching a stable release but we also could use some help. Are you a good copywriter? Are you an aspiring perl developer? Do you have leet designer skills? Your help is appreciated!','2005-07-23 01:52:20','andreas_news','Owner','0','Developers needed');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('We proudly announce a new beta release, version 1.0_05, aptly codenamed <i>Taj Mahal</i>.\r\nThis version introduces a feature freeze. All known issues and bugs will be fixed. Check the ChangeLog listing for all changes in this\r\nrelease and the Download section to get it now! \r\n','2005-07-23 13:25:13','andreas_news','Owner','0','New Beta release');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.1 (codename Burton) is the new stable release. Major changes include:\r\n<dir><li>Updated layout and new styles</li>\r\n<li>Fixed large number of bugs</li>\r\n<li>Added File Manager and Administration Access control</li>\r\n</dir>See the <a href=\"changelog.html\">ChangeLog</a> for full listing.','2006-02-19 15:13:55','andreas_news','Owner','0','Released v1.1 Stable (Burton)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.2 beta (codename Baldrick) is a beta for the upcoming version 1.2 release. Major changes include:\r\n\r\n<dir><li>Updated layout and new styles</li>\r\n<li>Fixed small number of bugs</li>\r\n<li>Support for mod_perl 2</li>\r\n<li>Support for int\'l</li>\r\n<li>Support for Postgresql as RDBMS</li>\r\n</dir>See the <a href=\"changelog.html\">ChangeLog</a> for full listing.\r\n','2006-05-16 23:12:44','andreas_news','Owner','0','Released v1.2 Beta (Baldrick)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.2 stable (codename Blackadder) is now available for download. Major changes include:\r\n<dir><li>Updated layout and added <b>8</b> new styles</li>\r\n<li>Fixed a number of bugs and added security measures</li> \r\n<li>Code cleanup and speedup (database handling, API)</li>\r\n<li>Added extra documentation : Quickstart guide for Styles</li>\r\n<li>Fixed in Package : Added (finally) support for logging</li>\r\n</dir>See the <a href=\"changelog.html\">ChangeLog</a> for full listing.\r\n','2006-12-27 18:24:22','news','Owner','0','Released v1.2 Stable (Blackadder)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('We proudly announce a new beta release, version 1.0_05, aptly codenamed <i>Taj Mahal</i>.\r\nThis version introduces a feature freeze. All known issues and bugs will be fixed. Check the ChangeLog listing for all changes in this\r\nrelease and the Download section to get it now! \r\n','2005-07-23 13:25:13','rssnews','Owner','0','New Beta release');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.1 (codename Burton) is the new stable release. Major changes include:\r\n<dir><li>Updated layout and new styles</li>\r\n<li>Fixed large number of bugs</li>\r\n<li>Added File Manager and Administration Access control</li>\r\n</dir>See the <a href=\"changelog.html\">ChangeLog</a> for full listing.','2006-02-19 15:13:55','rssnews','Owner','0','Released v1.1 Stable (Burton)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.2 beta (codename Baldrick) is a beta for the upcoming version 1.2 release. Major changes include:\r\n\r\n<dir><li>Updated layout and new styles</li>\r\n<li>Fixed small number of bugs</li>\r\n<li>Support for mod_perl 2</li>\r\n<li>Support for int\'l</li>\r\n<li>Support for Postgresql as RDBMS</li>\r\n</dir>See the <a href=\"changelog.html\">ChangeLog</a> for full listing.\r\n','2006-05-16 23:12:44','rssnews','Owner','0','Released v1.2 Beta (Baldrick)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.2 stable (codename Blackadder) is now available for download. Major changes include:\r\n<dir><li>Updated layout and added <b>8</b> new styles</li>\r\n<li>Fixed a number of bugs and added security measures</li> \r\n<li>Code cleanup and speedup (database handling, API)</li>\r\n<li>Added extra documentation : Quickstart guide for Styles</li>\r\n<li>Fixed in Package : Added (finally) support for logging</li>\r\n</dir>See the <a href=\"changelog.html\">ChangeLog</a> for full listing.\r\n','2006-12-27 18:24:22','rssnews','Owner','0','Released v1.2 Stable (Blackadder)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.22 Bugfix release (codename Termite) is now available for download. <b>Upgrading is recommended!</b> This packages fixes 2 of the vulnerabilities as reported by Secunia:<ol>\r\n<li>Fixed in Admin : Referer check</li>\r\n<li>Fixed in Admin : Arbitrary password</li>\r\n</ol>\r\nSee the <a href=\"install.html\">Installation documentation</a> for upgrading instructions. This package can be used as upgrade and reinstallation source. The affected package (version 1.2) will be removed from download listings. ','2007-08-22 22:46:42','news','Owner','0','Released v1.22 Bugfix (Termite)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.3 beta (codename Bernd) is a beta for the upcoming version 1.3 release. Major changes include:\r\n<dir>\r\n<li>Added 5 plugins (Slides, Picasa Gallery, Edit Page, Tags, Messages as RSS)</li>\r\n<li>Added admin plugins (Attributes, Upload As.., Caching, ..</li>\r\n<li>Added initial code for CGI support</li>\r\n<li>Added Content Wizard</li>\r\n<li>Support for locked content, guessing mime types, binary body,..)</li>\r\n<li>GUI changes..</li>\r\n</dir>See the <a href=\"changelog.html\">ChangeLog</a> for full listing.\r\n','2007-08-22 22:50:58','news','Owner','0','Released v1.3 Beta (Bernd)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.22 Bugfix release (codename Termite) is now available for download. <b>Upgrading is recommended!</b> This packages fixes 2 of the vulnerabilities as reported by Secunia:<ol>\n<li>Fixed in Admin : Referer check</li>\n<li>Fixed in Admin : Arbitrary password</li>\n</ol>\nSee the <a href=\"install.html\">Installation documentation</a> for upgrading instructions. This package can be used as upgrade and reinstallation source. The affected package (version 1.2) will be removed from download listings. ','2007-08-22 22:46:42','andreas_news','Owner','0','Release v1.22 Bugfix (Termite)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.22 Bugfix release (codename Termite) is now available for download. <b>Upgrading is recommended!</b> This packages fixes 2 of the vulnerabilities as reported by Secunia:<ol>\n<li>Fixed in Admin : Referer check</li>\n<li>Fixed in Admin : Arbitrary password</li>\n</ol>\nSee the <a href=\"install.html\">Installation documentation</a> for upgrading instructions. This package can be used as upgrade and reinstallation source. The affected package (version 1.2) will be removed from download listings. ','2007-08-22 22:46:42','rssnews','Owner','0','Release v1.22 Bugfix (Termite)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.3 beta (codename Bernd) is a beta for the upcoming version 1.3 release. Major changes include:\n<dir>\n<li>Added 5 plugins (Slides, Picasa Gallery, Edit Page, Tags, Messages as RSS)</li>\n<li>Added admin plugins (Attributes, Upload As.., Caching, ..</li>\n<li>Added initial code for CGI support</li>\n<li>Added Content Wizard</li>\n<li>Support for locked content, guessing mime types, binary body,..)</li>\n<li>GUI changes..</li>\n</dir>See the <a href=\"changelog.html\">ChangeLog</a> for full listing.','2007-08-22 22:50:58','rssnews','Owner','0','Released v1.3 Beta (Bernd)');
insert into message (body,mdate,mgroup,owner,parent,subject) values ('Spine v1.3 beta (codename Bernd) is a beta for the upcoming version 1.3 release. Major changes include:\n<dir>\n<li>Added 5 plugins (Slides, Picasa Gallery, Edit Page, Tags, Messages as RSS)</li>\n<li>Added admin plugins (Attributes, Upload As.., Caching, ..</li>\n<li>Added initial code for CGI support</li>\n<li>Added Content Wizard</li>\n<li>Support for locked content, guessing mime types, binary body,..)</li>\n<li>GUI changes..</li>\n</dir>See the <a href=\"changelog.html\">ChangeLog</a> for full listing.','2007-08-22 22:50:58','andreas_news','Owner','0','Released v1.3 Beta (Bernd)');

