insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Caching','admin/cache/','10','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Upload As','admin/uploadas/','10','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Sourceforge','sourceforge.html','23','10','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Alt Datatypes','alternate.html','23','9','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Developing','developing.html','23','8','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','License','license.html','23','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','FAQ','faq.html','23','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Quickstart : Style','quickstart2.html','23','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Quickstart : Content','quickstart.html','23','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Tags','tags.html','23','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Styles','styles.html','23','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','23','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','22','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','22','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','22','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','21','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','21','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','21','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','21','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','21','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','21','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','21','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','20','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','20','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','20','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','20','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','20','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','20','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','20','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','18','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','18','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','18','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','18','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','18','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','18','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','18','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','17','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','17','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','17','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','17','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','17','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','17','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','17','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','16','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','16','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','16','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','16','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','16','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','16','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Sourceforge Project Information','sourceforge.html','4','12','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Developers','developers.html','2','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','16','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','15','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','15','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','15','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','15','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','15','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','15','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','15','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','14','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','14','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','14','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Export SQL','admin/export/','10','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','13','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','13','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','13','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','13','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','13','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','13','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','13','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','14','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','14','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','14','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Language','admin/language/','10','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','14','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','9','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','9','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','9','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','9','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','9','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','9','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','9','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','FAQ, Tutorials, ...','','6','10','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Lots of pictures','','6','12','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Administrate your site','','6','14','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Get it here','','6','8','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','All the stuff inside','','6','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation notes','','6','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','5','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','5','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','5','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','5','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','5','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','8','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','8','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','8','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','8','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','8','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','8','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','8','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','7','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','7','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','7','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','7','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','7','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','7','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','7','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About the site','','6','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','6','13','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','5','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','6','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','5','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','6','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','6','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','6','9','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','6','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','6','11','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Alternative Datatypes','alternate.html','4','11','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Quickstart guide - Style','quickstart2.html','4','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Available Styles','styles.html','4','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Tips & Tricks','tips.html','4','13','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Usergroups','admin/usergroup','1','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Admin Access','admin/adminaccess/','1','10','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','3','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','ChangeLog','changelog.html','4','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','FAQ','faq.html','4','8','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','3','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','3','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','3','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Documentation','docs.html','2','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','3','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','3','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Login','login.html','2','8','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Logout','?button=logout','1','11','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','File Manager','admin/file/','1','9','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Statistics','admin/statistics/','1','8','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Users','admin/user/','1','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Macros','admin/macro/','1','5','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Messages','admin/message/','1','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','NavBar','admin/navbar/','1','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Style','admin/style/','1','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Content','admin/content/','1','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','2','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Developing for SPINE','developing.html','4','10','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Download','download.html','2','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Features','features.html','2','3','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation','install.html','2','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','About','index.html','2','1','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Using tags in your content','tags.html','4','2','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Development ToDo list','todo.html','4','7','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Screenshots','screenshots.html','3','6','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Quickstart guide - Content','quickstart.html','4','4','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','License','license.html','4','9','','','','');
insert into navbarbuttons (border,class,color,font,height,image,label,link,navbar,position,size,style,target,width) values ('0','','','','','','Installation Notes','install.html','4','1','','','','');

